### ISSUE TITLE
Load from string?

### ISSUE THREAD

**Issue by VinceG** [hassankhan/config#51]
Was this discussed before? i couldn't find an issue about it. 

Loading an XML from string will be beneficial since sometimes we don't have a file saved on the file system to load.

**Comment by DavidePastore** [comment]
I agree with you, it could be a nice feature. What do you think @hassankhan?

**Comment by hassankhan** [comment]
If I'm not mistaken, you could subclass `AbstractConfig`, and then parse the XML into an array yourself and pass it into the constructor method. We _could_ support it - just not sure a lot of people need the functionality :smile:

**Comment by fengkaijia** [comment]
There's indeed needs. E.g. when the config file has configurations for plugins, and we only want to pass part of the config to the plugin for isolation. So that would be like:

```php
$config = new Config('config.yaml');
$plugin = new $plugin_name(new Config($config->plugin->plugin_name));
```

This is indeed just a class extends `AbstractConfig` without anything, but having it at config package is better than creating it at our own package.

**Comment by filips123** [comment]
I've created pull request #111 for loading from string.
