### ISSUE TITLE
Lazy load supported?

### ISSUE THREAD

**Issue by lezhnev74** [hassankhan/config#90]
Hi!

From the README file it was not clear if it supported lazy loading.
Can I set the folder where all my config files are stored and include only those which were requested on runtime?

**Comment by DavidePastore** [comment]
Hi @lezhnev74. Sorry for the delay. No, you can't set a folder and include only the config files that are requested. [Here](https://github.com/hassankhan/config/blob/06ac500348af033f1a2e44dc357ca86282626d4a/src/Config.php#L45-L73) you can see it loads all the files and parses all of them. Otherwise how would it be possible to know in advance in which file the given key config is?
